### ISSUE TITLE
image Preprocessing.py

### ISSUE THREAD

**Issue by ad4013** [Karthikeyu/Indian-sign-language-recognition#1]
when it is run it shows
Value error:Expected 2d array,got 1D array instead

The dataset was downloaded and extracted and pasted directly to root directory

**Comment by Karthikeyu** [comment]
Hey, Hi. Can you tell from which line it is throwing the error?

**Comment by ad4013** [comment]
is ipu.path is  where the path should be placed because when i did that the error has gone but now 
this comes: surf = cv2.xfeatures2d.SURF_create( )

error: OpenCV(4.2.0) C:\projects\opencv-python\opencv_contrib\modules\xfeatures2d\src\surf.cpp:1029: error: (-213:The function/feature is not implemented) This algorithm is patented and is excluded in this configuration; Set OPENCV_ENABLE_NONFREE CMake option and rebuild the library in function 'cv::xfeatures2d::SURF::create'

**Comment by Karthikeyu** [comment]
Great. SURF is not included in the latest version open cv. You can downgrade it .. You can use these commands 
pip install opencv-python==3.4.2.16
pip install opencv-contrib-python==3.4.2.16

**Comment by ad4013** [comment]
It worked but now:


length of train features are 33600
length of test features are 8400
length of all train discriptors is 15735482
Mini batch K-Means started.
15735482 descriptors before clustering........
The console  frozen here...

**Comment by ad4013** [comment]
the console got frozen here:
Test:--------- Label is Z and Count is 1197
(362, 64)
Test:--------- Label is Z and Count is 1198
(377, 64)
Test:--------- Label is Z and Count is 1199
length of train features are 33600
length of test features are 8400
length of all train discriptors is 15735482
Mini batch K-Means started.
15735482 descriptors before clustering

**Comment by Karthikeyu** [comment]
Hey, This is because of the RAM and CPU performance. While K-means clustering running, it takes a good amount of time to finish depending on the CPU and RAM. If your processer can't handle it, you can change the total number of images per class in imageprocessingutils file, by replacing TOTAL_IMAGES = 800. Now, for each class, only 800 images will be taken for training and testing which reduces load on cpu.

**Comment by ad4013** [comment]
Thank you so much man it worked,keep up the good work.........any ways to increase accuracy or to reduce noise

**Comment by Karthikeyu** [comment]
You are welcome and thank you :). During real-time recognition, the accuracy can be improved if you test in the outdoors with a good amount of sunlight and with the black background. Because the data set that I have created contains mostly similar images with the same light condition and background. If you can train the model with diverse data with different light conditions and different skin tones,  then I am sure it will be pretty amazing and robust.

**Comment by RockGod1997** [comment]
bro  while running the recogniseGesture.py file i am getting an error   in cv2.imshow("Video",frame) line 63 says the assertion failed is it because the t variable in (t,frame) is uninitialised?

**Comment by jeelnathani** [comment]
> Thank you so much man it worked,keep up the good work.........any ways to increase accuracy or to reduce noise

How much time did it took with 800 images per class?
